repos:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/repo.yaml
  projects:
    - /
pyup:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/pyup.yaml
  projects:
    - /
tools:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/python-tool.yaml
  projects:
    - /
